//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace org { namespace alljoyn { namespace example { namespace Toaster {

// This class, and the associated EventArgs classes, exist for the benefit of JavaScript developers who
// do not have the ability to implement IToasterService. Instead, ToasterServiceEventAdapter
// provides the Interface implementation and exposes a set of compatible events to the developer.
public ref class ToasterServiceEventAdapter sealed : [Windows::Foundation::Metadata::Default] IToasterService
{
public:
    // Method Invocation Events
    event Windows::Foundation::TypedEventHandler<ToasterServiceEventAdapter^, ToasterStartToastingCalledEventArgs^>^ StartToastingCalled;
    event Windows::Foundation::TypedEventHandler<ToasterServiceEventAdapter^, ToasterStopToastingCalledEventArgs^>^ StopToastingCalled;

    // Property Read Events
    event Windows::Foundation::TypedEventHandler<ToasterServiceEventAdapter^, ToasterGetVersionRequestedEventArgs^>^ GetVersionRequested;
    event Windows::Foundation::TypedEventHandler<ToasterServiceEventAdapter^, ToasterGetDarknessLevelRequestedEventArgs^>^ GetDarknessLevelRequested;
    
    // Property Write Events
    event Windows::Foundation::TypedEventHandler<ToasterServiceEventAdapter^, ToasterSetDarknessLevelRequestedEventArgs^>^ SetDarknessLevelRequested;

    // IToasterService Implementation
    virtual Windows::Foundation::IAsyncOperation<ToasterStartToastingResult^>^ StartToastingAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<ToasterStopToastingResult^>^ StopToastingAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    virtual Windows::Foundation::IAsyncOperation<ToasterGetVersionResult^>^ GetVersionAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<ToasterGetDarknessLevelResult^>^ GetDarknessLevelAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    virtual Windows::Foundation::IAsyncOperation<ToasterSetDarknessLevelResult^>^ SetDarknessLevelAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, _In_ byte value);
};

} } } } 
