//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace org { namespace alljoyn { namespace example { namespace Toaster {

ref class ToasterSignals;

public interface class IToasterSignals
{
    event Windows::Foundation::TypedEventHandler<ToasterSignals^, ToasterToastBurntReceivedEventArgs^>^ ToastBurntReceived;
};

public ref class ToasterSignals sealed : [Windows::Foundation::Metadata::Default] IToasterSignals
{
public:
    // Calling this method will send the ToastBurnt signal to every member of the session.
    void ToastBurnt();

    // This event fires whenever the ToastBurnt signal is sent by another member of the session.
    virtual event Windows::Foundation::TypedEventHandler<ToasterSignals^, ToasterToastBurntReceivedEventArgs^>^ ToastBurntReceived;

internal:
    void Initialize(_In_ alljoyn_busobject busObject, _In_ alljoyn_sessionid sessionId);
    void CallToastBurntReceived(_In_ ToasterSignals^ sender, _In_ ToasterToastBurntReceivedEventArgs^ args);

private:
    alljoyn_busobject m_busObject;
    alljoyn_sessionid m_sessionId;

    alljoyn_interfacedescription_member m_memberToastBurnt;
};

} } } } 
