//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGen.exe
//   Version: 1.0.0
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Extension Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UAP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGen - Invoke the following command with a valid 
//   Introspection XML file:
//     AllJoynCodeGen -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace com { namespace microsoft { namespace sample {

ref class toasterConsumer;

public ref class toasterStartToastingResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    
    static toasterStartToastingResult^ CreateSuccessResult()
    {
        auto result = ref new toasterStartToastingResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }
    
    static toasterStartToastingResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new toasterStartToastingResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

public ref class toasterStopToastingResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    
    static toasterStopToastingResult^ CreateSuccessResult()
    {
        auto result = ref new toasterStopToastingResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }
    
    static toasterStopToastingResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new toasterStopToastingResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

public ref class toasterJoinSessionResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property toasterConsumer^ Consumer
    {
        toasterConsumer^ get() { return m_consumer; }
    internal:
        void set(_In_ toasterConsumer^ value) { m_consumer = value; }
    };

private:
    int32 m_status;
    toasterConsumer^ m_consumer;
};

public ref class toasterGetDarknessResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property uint32 Darkness
    {
        uint32 get() { return m_value; }
    internal:
        void set(_In_ uint32 value) { m_value = value; }
    }

    static toasterGetDarknessResult^ CreateSuccessResult(_In_ uint32 value)
    {
        auto result = ref new toasterGetDarknessResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Darkness = value;
        return result;
    }

    static toasterGetDarknessResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new toasterGetDarknessResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
    uint32 m_value;
};

} } } 
