//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGen.exe
//   Version: 1.0.0
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Extension Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UAP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGen - Invoke the following command with a valid 
//   Introspection XML file:
//     AllJoynCodeGen -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace com { namespace microsoft { namespace sample {

// This class, and the associated EventArgs classes, exist for the benefit of JavaScript developers who
// do not have the ability to implement ItoasterService. Instead, toasterServiceEventAdapter
// provides the Interface implementation and exposes a set of compatible events to the developer.
public ref class toasterServiceEventAdapter sealed : [Windows::Foundation::Metadata::Default] ItoasterService
{
public:
    // Method Invocation Events
    event Windows::Foundation::TypedEventHandler<toasterServiceEventAdapter^, toasterStartToastingCalledEventArgs^>^ StartToastingCalled;
    event Windows::Foundation::TypedEventHandler<toasterServiceEventAdapter^, toasterStopToastingCalledEventArgs^>^ StopToastingCalled;

    // Property Read Events
    event Windows::Foundation::TypedEventHandler<toasterServiceEventAdapter^, toasterGetDarknessRequestedEventArgs^>^ GetDarknessRequested;
    
    // Property Write Events
    event Windows::Foundation::TypedEventHandler<toasterServiceEventAdapter^, toasterSetDarknessRequestedEventArgs^>^ SetDarknessRequested;

    // ItoasterService Implementation
    virtual Windows::Foundation::IAsyncOperation<toasterStartToastingResult^>^ StartToastingAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<toasterStopToastingResult^>^ StopToastingAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    virtual Windows::Foundation::IAsyncOperation<toasterGetDarknessResult^>^ GetDarknessAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    virtual Windows::Foundation::IAsyncOperation<int>^ SetDarknessAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, _In_ uint32 value);
};

} } } 
