//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace org { namespace alljoyn { namespace example { namespace Toaster {

ref class ToasterConsumer;

public ref class ToasterStartToastingResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    
    static ToasterStartToastingResult^ CreateSuccessResult()
    {
        auto result = ref new ToasterStartToastingResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }
    
    static ToasterStartToastingResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new ToasterStartToastingResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

public ref class ToasterStopToastingResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    
    static ToasterStopToastingResult^ CreateSuccessResult()
    {
        auto result = ref new ToasterStopToastingResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }
    
    static ToasterStopToastingResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new ToasterStopToastingResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

public ref class ToasterJoinSessionResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property ToasterConsumer^ Consumer
    {
        ToasterConsumer^ get() { return m_consumer; }
    internal:
        void set(_In_ ToasterConsumer^ value) { m_consumer = value; }
    };

private:
    int32 m_status;
    ToasterConsumer^ m_consumer;
};

public ref class ToasterGetVersionResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property uint16 Version
    {
        uint16 get() { return m_value; }
    internal:
        void set(_In_ uint16 value) { m_value = value; }
    }

    static ToasterGetVersionResult^ CreateSuccessResult(_In_ uint16 value)
    {
        auto result = ref new ToasterGetVersionResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Version = value;
        return result;
    }

    static ToasterGetVersionResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new ToasterGetVersionResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
    uint16 m_value;
};

public ref class ToasterGetDarknessLevelResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property byte DarknessLevel
    {
        byte get() { return m_value; }
    internal:
        void set(_In_ byte value) { m_value = value; }
    }

    static ToasterGetDarknessLevelResult^ CreateSuccessResult(_In_ byte value)
    {
        auto result = ref new ToasterGetDarknessLevelResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->DarknessLevel = value;
        return result;
    }

    static ToasterGetDarknessLevelResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new ToasterGetDarknessLevelResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
    byte m_value;
};

public ref class ToasterSetDarknessLevelResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    static ToasterSetDarknessLevelResult^ CreateSuccessResult()
    {
        auto result = ref new ToasterSetDarknessLevelResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }

    static ToasterSetDarknessLevelResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new ToasterSetDarknessLevelResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

} } } } 
